language: ruby
rvm:
- 2.2
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"

branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: VIZ5D0yT3piQxdS88b9591sz9TE08g6slWooYNcZdW0JiksDeTbHrkgZQ9rnwLhDj+oOw5vhABfp7VPYtzAWtiU6hKUjbxBHSra62DprKKBbZ1SgL98+n77dDOnLncB+gzH9fkQ6fidOoLv7cM7Yv65iFBpq/+3np098Ul14bo70nxP5+Mcko8eh6WtCMbfQWndQPgfCQg8uURSH/UDQCpYc9SPj8odFlfHHuxmWiKobvCP2kWJs8v+8DfkdSEdZJ5Bpwr5b6Ypo0Q0laK0W3UjzADDCBMHwLP6JXjo/rXtssIMIRxBZXTpBs3vB2f5+M/msLz1cHipwcfargmCEp06iebr0VFOIAbnq3uZVAB+mT1w8PRtTslSn5qSgVAnqUbTeURPFvg7SRR/Ax7mosV5vcGZ4GzuqDWNdNzIKzQCVelyLoVwCFzoX6ZjPOW5Z/SVkmNvGDyU6Ok0SmkL66YYU4LPoCvhS+saxLCUdxuYcoZa3tXfB6+7o4DKz4hKAP9l2zNlMgaw0HE5UrnBkXraABZfakaenRDlPPujtqctAVQrudHVQA6qnFaganU1y8EwWEVplaxo1x7upTfh2nckfhdkXklaOAqpkZYyKqVbvik9QPf9WzpvFvtZUcXMbaeRZ2G4sFIMugP4RuWMiye+BmP9wVDxzvqMDU4cle5o=
  - secure: DBf/rcydusqg+fxTf5+rZUDE6gZoMaqiG4VgMZlqSoxarefsluCVi3iKOlrJZSp1RXUxp98AkmNC5a2ezStPd/4yKWaRqvxhCYpsvvPNIbnSkxegIFjVDcsGxJ0Stx7PrEpXPfMPW4y5PNc5PdZdbwWgsN0u4jvWvPDVXcicTS+kFh+HCpFyPH/2TbdVcFLiIWTuF1wTI8Ux95SVmxbS8lwRAFuAQS1Zly/CbvNjHWcAMHuHdjgjCkKoX2rggvUN9uMaiLTkC1U0O9MVKqO25nayiaAbBEKYJnAnhO7jfT5ckqUtvyj76rXruX5GBTBbQYAg0+XYZui2jbXvjEGImdEO4JVkM6zFxHB2/FQ4ndjmEpIMfPXsEYoeM8VJZIlkulD+MdmJ7djOcCC3NCWfZ3LG2UNvGOqKV2v8jKL+xtgXvELurcOn9wrg6kvD0okI9qVIvKZ4F5jC45GzoaBDkLPS+8nHPbzurQij/QLM0n0C/SjMqQEyPLOO9Ps7U3ByQzVMOlsWk6uuBEZVNRzAQnUJQ4RfUiSpB4bOiUbjJo/cH5RPNLMQiY7PND/4luuYKnSUufCjlJS6lv9Q7+djqd+kCIAON35AheypQZt3HTK75g0Tn42gBReR/f984Ua6h9J73G0RJIJF9Z2OIVlfh7nsVojA1p40cEHm310AmHI=

after_success:
    "bundle exec s3_website push"